export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENT_F = "FETCH_INGREDIENT_F";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

export const PLACE_ORDER_INITIATED = "PLACE_ORDER_INITIATED";
export const FETCH_ORDER_INITIATED = "FETCH_ORDER_INITIATED";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILURE = "FETCH_ORDER_FAILURE";
export const RESET_ORDER_PLACED_STATUS = "RESET_ORDER_PLACED_STATUS";

export const AUTH_SIGN_UP_INITIATED = "AUTH_SIGN_UP_INITIATED";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";
export const AUTH_TOKEN_LOADED_ON_APP_START = "AUTH_TOKEN_LOADED_ON_APP_START";

export const AUTH_SIGN_IN_INITIATED = "AUTH_SIGN_IN_INITIATED";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";

export const SAGA_AUTH_SIGN_OUT_INITIATE = "SAGA_AUTH_SIGN_OUT_INITIATE";
export const SAGA_PERFORM_AUTH_SIGN_OUT = "SAGA_PERFORM_AUTH_SIGN_OUT";
export const SAGA_PERFORM_AUTO_SIGIN_CHECK = "SAGA_PERFORM_AUTO_SIGIN_CHECK";
export const SAGA_PERFORM_AUTH_SIGN_IN_AYSNC =
  "SAGA_PERFORM_AUTH_SIGN_IN_AYSNC";

export const SAGA_FETCH_INGREDIENTS = "SAGA_FETCH_INGREDIENTS";

export const SAGA_FETCH_ORDER = "SAGA_FETCH_ORDER";
export const SAGA_PLACE_ORDER = "SAGA_PLACE_ORDER";
